# Generated by Django 5.0 on 2024-02-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producct_image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
